"""create tables

Revision ID: f91243ed93e0
Revises: 
Create Date: 2026-09-22 12:49:58.750270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f91243ed93e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=34), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('important', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_snapshots',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('points_done', sa.Integer(), nullable=False),
    sa.Column('points_total', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'snapshot_date')
    )
    op.create_table('steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('AI', 'Manual', name='source'), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('points in (1, 2, 3, 5, 8)', name='valid_points'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_project_id'), 'steps', ['project_id'], unique=False)
    op.create_table('verdicts',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('verdict_date', sa.Date(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'verdict_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_steps_project_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_table('daily_snapshots')
    op.drop_table('projects')
    # create_table('steps') creates this enum type implicitly; dropping the
    # tables does not remove it, so a re-upgrade would fail on "already exists".
    sa.Enum('AI', 'Manual', name='source').drop(op.get_bind())
    # ### end Alembic commands ###
